[package]
distribution = "2201.4.1"
org="ballerinax"
name = "redis"
version="2.4.1"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases",  "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-redis"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../redis-utils/target/redis-2.4.1.jar"
groupId = "org.ballerinalang"
artifactId = "redis-utils"
module = "redis-utils" 
version="2.4.1"

[[platform.java11.dependency]]
groupId = "io.lettuce"
artifactId = "lettuce-core"
version = "5.1.8.RELEASE"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-kqueue"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-epoll"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.94.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.94.Final"
