name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: 11

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                ./gradlew build

            - name: Set Up Ballerina
              uses: ballerina-platform/setup-ballerina@v1.1.0
              with:
                version: latest

            - name: Ballerina Build
              working-directory: ./redis
              run: bal pack

            - name: Ballerina Test
              working-directory: ./redis
              run: bal test --code-coverage

            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./redis/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
